### ISSUE TITLE
Investigate whether we support entity reference deletion

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#243] opened 2020-05-13 00:29 UTC
From [11.4.6.2 Remove a Reference to an Entity](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_RemoveaReferencetoanEntity):

> A successful DELETE request to the URL that represents a reference to a related entity removes the relationship to that entity.
> 
> In OData 4.0, the entity reference to be removed within a collection-valued navigation property is the URL that represents the collection of related references, with the reference to be removed identified by the $id query option. OData 4.01 services additionally support using the URL that represents the reference of the collection member to be removed, identified by key, as described in [OData‑URL].
> 
> For single-valued navigation properties, the $id query option MUST NOT be specified.
> 
> The DELETE request MUST NOT violate any integrity constraints in the data model.
> 
> On successful completion, the response MUST be 204 No Content and contain an empty body.

We have the following metadata:

```xml
<EntityType Name="group" BaseType="graph.directoryObject" OpenType="true"
  <NavigationProperty Name="acceptedSenders" Type="Collection(graph.directoryObject)" ContainsTarget="true" />
  <NavigationProperty Name="rejectedSenders" Type="Collection(graph.directoryObject)" ContainsTarget="true" />
</EntityType>
```

We are certain that the definition is incorrect as the [documentation shows this to be a reference](https://docs.microsoft.com/en-us/graph/api/group-post-acceptedsenders?view=graph-rest-1.0&tabs=http) when adding an acceptedSender.

For [removing a reference](https://docs.microsoft.com/en-us/graph/api/group-delete-acceptedsenders?view=graph-rest-1.0&tabs=http), we will need to support:

```http
DELETE /groups/{id}/acceptedSenders/$ref?$id=https://graph.microsoft.com/v1.0/users/{user-id}
```

@zengin  
[AB#7084](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7084)

**Comment by zengin** [comment] 2023-04-05 20:22
duplicate of #471 with more information

**Closed by zengin** 2023-04-05 20:22 UTC
Labels: investigation needed, promote
